stages:
  preprocess:
    cmd: python -m ahah.preprocess
    deps:
      - ahah/preprocess.py

      - data/raw/nhs
      - data/raw/onspd
      - data/raw/oproad
      - data/raw/osm
    outs:
      - data/processed/onspd/postcodes.parquet
      - data/processed/oproad/edges.parquet
      - data/processed/oproad/nodes.parquet
      - data/processed/bluespace.parquet
      - data/processed/dentists.parquet
      - data/processed/gpp.parquet
      - data/processed/hospitals.parquet
      - data/processed/pharmacies.parquet

  route:
    cmd: python -m ahah.route
    deps:
      - ahah/route.py

      - data/processed/onspd/postcodes.parquet
      - data/processed/oproad/edges.parquet
      - data/processed/oproad/nodes.parquet
      - data/processed/bluespace.parquet
      - data/processed/dentists.parquet
      - data/processed/gpp.parquet
      - data/processed/hospitals.parquet
      - data/processed/pharmacies.parquet
    outs:
      - data/out/bluespace_distances.parquet
      - data/out/dentists_distances.parquet
      - data/out/gpp_distances.parquet
      - data/out/hospitals_distances.parquet
      - data/out/pharmacies_distances.parquet

  air:
    cmd: python -m ahah.air_lsoa
    deps:
      - ahah/air_lsoa.py

      - data/raw/air/mapno22022.csv
      - data/raw/air/mappm102022g.csv
      - data/raw/air/mapso22022.csv
    outs:
      - data/out/air/AIR-LSOA21CD.csv
  aggregate:
    cmd: python -m ahah.aggregate_lsoa
    deps:
      - ahah/aggregate_lsoa.py

      - data/processed/onspd/postcodes.parquet
      - data/processed/oproad/edges.parquet
      - data/processed/oproad/nodes.parquet
      - data/processed/bluespace.parquet
      - data/processed/dentists.parquet
      - data/processed/gpp.parquet
      - data/processed/hospitals.parquet
      - data/processed/pharmacies.parquet
      - data/out/air/AIR-LSOA21CD.csv
      - data/raw/gov/LSOA2021/LSOA_2021_EW_BFC_V8.shp
      - data/raw/gov/SG_DataZone/SG_DataZone_Bdry_2011.shp
      - data/raw/ndvi/spatia_orbit_postcode_V1_210422.csv
    outs:
      - data/out/ahah/AHAH-V4-LSOA21CD.csv

  index:
    cmd: python -m ahah.create_index
    deps:
      - ahah/create_index.py

      - data/out/ahah/AHAH-V4-LSOA21CD.csv
      - data/processed/2024_08_21_CILLIANBERRAGAN_AHAHV4_LDC.csv

    outs:
      - "data/out/ahah/AHAH_V4.csv"
