stages:
  preprocess:
    cmd: python -m ahah.preprocess
    deps:
      - data/raw/nhs
      - data/raw/onspd
      - data/raw/oproad
      - data/raw/osm
    outs:
      - data/processed/onspd/postcodes.parquet
      - data/processed/oproad/edges.parquet
      - data/processed/oproad/nodes.parquet
      - data/processed/bluespace.parquet
      - data/processed/dentists.parquet
      - data/processed/gpp.parquet
      - data/processed/hospitals.parquet
      - data/processed/pharmacies.parquet

  routing:
    cmd: python -m ahah.routing
    deps:
      - data/processed
    outs:
      - data/out/distances_bluespace.parquet
      - data/out/distances_dentists.parquet
      - data/out/distances_gpp.parquet
      - data/out/distances_hospitals.parquet
      - data/out/distances_pharmacies.parquet

  air:
    cmd: python -m ahah.air
    deps:
      - data/raw/air
    outs:
      - data/out/air/msoa-2021-air.csv
