[project]
name = "ahah"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "cjber", email = "cjberragan@gmail.com" }
]
dependencies = [
    "cuml-cu12>=24.2.0",
    "cugraph-cu12>=24.2.0",
    "cuspatial-cu12>=24.2.0",
    "cuproj-cu12>=24.2.0",
    "rich>=13.7.1",
    "tqdm>=4.66.2",
    "ipdb>=0.13.13",
]
readme = "README.md"
requires-python = ">= 3.10"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "ipython>=8.23.0",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/ahah"]
